#pragma once

#include "app_config.h"

#include <string>
#include <string_view>

namespace voicestick {

// 稳定语义 key，不要用英文原文做 key，以免文案微调破坏索引。
enum class StringId {
    // 通用
    kOk,
    kCancel,
    kSave,
    kClose,

    // 设置窗口
    kSettingsTitle,
    kSettingsLanguage,
    kSettingsLanguageSystem,
    kSettingsLanguageEnglish,
    kSettingsLanguageChineseSimplified,
    kSettingsProvider,
    kSettingsApiKey,
    kSettingsResourceId,
    kSettingsHotwords,
    kSettingsHotwordsHint,
    kSettingsLlmBaseUrl,
    kSettingsLlmApiKey,
    kSettingsLlmModel,
    kSettingsRefineText,
    kSettingsRefinePrompt,
    kSettingsLaunchAtLogin,
    kSettingsSelectionHotword,
    kSettingsSelectionHotwordHint,
    kSettingsSectionHotwordProcess,
    kSettingsHotwordProcessEnable,
    kSettingsHotwordProcessPrompt,
    kSettingsDebugAudio,
    kSettingsShowImuDebug,
    kSettingsImuWakeSensitivity,
    kSettingsImuWakeSensitivityLow,
    kSettingsImuWakeSensitivityMedium,
    kSettingsImuWakeSensitivityHigh,
    kSettingsTapToArrow,
    kSettingsTapSensitivity,
    kSettingsAirMouseSensitivityX,
    kSettingsAirMouseSensitivityY,
    kSettingsOutputTarget,
    kSettingsOutputTargetFocusedApp,
    kSettingsOutputTargetSubtitle,
    kSettingsOutputTargetWechatInputMethod,
    kSettingsWechatHotkey,
    kSettingsWechatVirtualMic,
    kSettingsWechatAutoSwitch,
    kSettingsWechatVirtualMicCapture,
    kSettingsTriggerMode,
    kSettingsTriggerModeHold,
    kSettingsTriggerModeClick,
    kSettingsDebugDir,
    kSettingsChooseDir,
    kSettingsOpenConfigFolder,
    kSettingsApplyTrial,
    kSettingsApplyingTrial,
    kSettingsTrialApplied,
    kSettingsTrialPageOpened,
    kSettingsTrialFailedTitle,
    kSettingsTrialFailedMessage,
    kSettingsSaved,
    kSettingsSaveFailed,
    kSettingsSectionGeneral,
    kSettingsSectionAsr,
    kSettingsSectionRefine,
    kSettingsSectionOutput,
    kSettingsSectionDevice,
    kSettingsSectionSystem,
    kSettingsSectionAudioFiles,
    kSettingsOpenSpectrogram,
    kSettingsSpectrogramNotFound,
    kSettingsDeveloperMode,

    // 托盘菜单
    kMenuPairDevice,
    kMenuSettings,
    kMenuQuit,
    kMenuRelaunchElevated,
    kMenuWebsite,
    kMenuCheckAppUpdates,
    kMenuFlashTool,
    kMenuRestoreLastInput,
    kMenuInteraction,
    kMenuHoldToTalk,
    kMenuClickToTalk,
    kMenuAutoEnter,
    kMenuLaunchAtLogin,
    kMenuSelectionHotword,
    kMenuOutput,
    kMenuOutputFocusedApp,
    kMenuOutputSubtitle,
    kMenuTranslation,
    kMenuOriginal,
    kMenuThemeColor,
    kMenuThemeSize,
    kMenuOverlayPosition,
    kMenuForgetDevice,
    kMenuUpdateFirmware,
    kMenuUpdateFirmwareFromFile,
    kMenuFirmwareUpToDate,
    kMenuHotkey,
    kMenuHotkeyEnabled,
    kMenuHotkeyCustom,
    kMenuHotkeyConflictTitle,
    kMenuHotkeyConflictBody,

    // 设备状态
    kStatusNoPairedDevices,
    kStatusScanning,
    kStatusConnected,
    kStatusDisconnected,
    kStatusReady,
    kStatusAirMouseActive,

    // 配对窗口
    kPairTitle,
    kPairScanning,
    kPairNoDevices,
    kPairConnect,
    kPairConnecting,
    kPairConnected,
    kPairFailed,
    kPairSignal,
    kPairBluetoothAddress,
    kPairManualIdHint,
    kPairButton,
    kPairRetry,
    kPairStillScanning,
    kPairScanFailed,
    kPairAlreadyPaired,
    kPairWaitingForName,
    kPairSelectDeviceWithId,
    kPairSelectDevice,
    kPairEnterManualId,
    kPairSavedManualWaiting,
    kPairPairingDevice,
    kPairConnectedFinishing,
    kPairPairedDevice,
    kPairPairedDeviceFirmware,
    kPairTimedOut,
    kPairFoundCount,
    kPairScanningCount,
    // 双模扫描候选/设备类型标签与小米遥控器 OS 配对引导
    kDeviceTypeVoiceStick,
    kDeviceTypeXiaomiRemote,
    kDeviceTypeXiaomiRemote2Pro,
    kPairXiaomiOsPairing,
    kPairXiaomiBondFailed,

    // 引导窗口
    kOnboardingTitle,
    kOnboardingSubtitle,
    kOnboardingGetStarted,
    kOnboardingSetupTitle,
    kOnboardingDeviceStep,
    kOnboardingAsrStep,
    kOnboardingReadyStep,
    kOnboardingBack,
    kOnboardingNext,
    kOnboardingFinish,
    kOnboardingDevicePairedContinue,
    kOnboardingPairDeviceTitle,
    kOnboardingPairDeviceDescription,
    kOnboardingPairDeviceInstruction,
    kOnboardingPairAnotherDevice,
    kOnboardingPairDeviceButton,
    kOnboardingChooseAsr,
    kOnboardingProvider,
    kOnboardingApiKey,
    kOnboardingResource,
    kOnboardingReadyTitle,
    kOnboardingReadyInstruction,
    kOnboardingApplyingTrial,
    kOnboardingTrialApplied,
    kOnboardingTrialOpenFailed,
    kOnboardingTrialPageOpened,
    kOnboardingTrialApplyFailed,
    kOnboardingPairDeviceFirst,
    kOnboardingSkipDeviceConfirm,
    kOnboardingEnterApiKey,
    kOnboardingDeviceNotPaired,
    kOnboardingDeviceSummary,
    kOnboardingAsrSummary,

    // 固件更新
    kFirmwareUpdateTitle,
    kFirmwareUpdateAvailable,
    kFirmwareUpdateRequired,
    kFirmwareUpdateButton,
    kFirmwareUpdateUpToDate,
    kFirmwareUpdating,
    kFirmwareUpdateSuccess,
    kFirmwareUpdateFailed,
    kFirmwareUpdateFinalizing,
    kFirmwareUpdateTransferring,
    kFirmwareUpdatedTitle,
    kFirmwareUpdatedDetail,
    kFirmwareCancellingTitle,
    kFirmwareCancellingDetail,
    kFirmwareDownloading,
    kFirmwareCheckFailed,
    kFirmwareChecking,
    kFirmwareUpdateAvailableMenu,
    kFirmwareLatestMenu,
    kFirmwareUpdateTo,
    kFirmwareUpdatePromptTitleRequired,
    kFirmwareUpdatePromptTitleAvailable,
    kFirmwareUpdatePromptBody,
    kFirmwareUpdateAdvancedComFlash,

    // 热键设置
    kHotkeyTitle,
    kHotkeyEnabled,
    kHotkeyPreset,
    kHotkeyCustomKey,
    kHotkeyCurrent,
    kHotkeyCaptureButton,
    kHotkeyCapturePrompt,
    kHotkeyHint,
    kHotkeyMissingModifier,
    kHotkeyConflictTitle,
    kHotkeyConflictMessage,

    // 云服务提示
    kCloudNeedsAttentionTitle,
    kCloudOpenPageQuestion,

    // 提权重启
    kRelaunchFailedTitle,
    kRelaunchFailedPath,
    kRelaunchFailedUac,
    kElevationNeededTitle,
    kElevationNeededBody,

    // 通知
    kNotificationPairedTitle,
    kNotificationManualPairSavedTitle,
    kNotificationManualPairSavedBody,
    kNotificationFirmwareUpdatedTitle,
    kNotificationFirmwareUpdatedBody,

    // 悬浮窗
    kOverlayListening,
    kOverlayThinking,
    kOverlayError,
    kOverlayAsrError,
    kOverlayNoSpeech,

    // 通知
    kNotificationHotkeyConflictTitle,
    kNotificationHotkeyConflictBody,

    // 划词添加热词
    kSelectionHotwordButton,
    kSelectionHotwordAddedTitle,
    kSelectionHotwordAddedBody,
    kSelectionHotwordDuplicateTitle,
    kSelectionHotwordDuplicateBody,
    kSelectionHotwordEmptyTitle,
    kSelectionHotwordEmptyBody,
    kSelectionHotwordTooLongTitle,
    kSelectionHotwordTooLongBody,
    kHotwordCandidateNotifyTitle,
    kHotwordCandidateNotifyBodySuffix,
    kSettingsHotwordCandidatesLabel,
    kSettingsHotwordCandidateAddButton,
    kSettingsHotwordCandidateDismissButton,

    // 热词处理（LLM 提炼）
    kHotwordProcessExtracting,
    kHotwordProcessAdded,
    kHotwordProcessAllDuplicate,
    kHotwordProcessEmptyResult,
    kHotwordProcessFailed,
    kHotwordProcessNoKey,

    // 编码器设置节
    kSettingsSectionEncoder,
    kSettingsEncoderToArrow,
    kSettingsEncoderRotationInvert,
    kSettingsEncoderRotateCwKey,
    kSettingsEncoderRotateCcwKey,
    kSettingsEncoderRotateFastThreshold,
    kSettingsEncoderRotateCwFastKey,
    kSettingsEncoderRotateCcwFastKey,
    kSettingsEncoderLedColor,
    kSettingsEncoderPressAction,
    kSettingsEncoderDoubleClickAction,
    kSettingsEncoderActionRecording,
    kSettingsEncoderActionKey,
    kSettingsEncoderLedRed,
    kSettingsEncoderLedGreen,
    kSettingsEncoderLedBlue,
    kSettingsEncoderLedYellow,
    kSettingsEncoderLedPurple,
    kSettingsEncoderLedCyan,
    kSettingsEncoderLedWhite,
    kSettingsEncoderLedOff,
    kSettingsEncoderInvalidKey,
    kSettingsEncoderRotateDecideWindow,
    kSettingsEncoderPressKey,
    kSettingsEncoderDoubleClickKey,

    // 设备级编码器设置（托盘设备子菜单入口 + 独立对话框）
    kMenuEncoderSettings,
    // {0} = 设备 ID（如 5A74）
    kEncoderSettingsTitle,
    kEncoderSettingsRestoreDefaults,
    // 设备级交互设置（托盘设备子菜单入口 + 独立对话框）
    kMenuInteractionSettings,
    // {0} = 设备 ID（如 5A74）
    kInteractionSettingsTitle,

    // 设备级遥控器设置（小米遥控器，托盘设备子菜单入口 + 独立对话框）
    kMenuRemoteSettings,
    // {0} = 设备 ID（如 RC-3A7F）
    kRemoteSettingsTitle,
    kSettingsRemoteGainDb,
    kSettingsRemoteDoubleClickMs,
    // 提示行：设置值在会话创建时消费，热更不重配已连接会话
    kRemoteSettingsEffectiveNextConnect,

    // 电池电压监测（托盘设备子菜单入口 + 独立监测窗口，仅连接设备显示）
    kMenuBatteryMonitor,
    // {0} = 设备 ID
    kBatteryMonitorTitle,
    kBatteryMonitorStart,
    kBatteryMonitorStop,
    kBatteryMonitorExportCsv,
    kBatteryMonitorExportPng,
    kBatteryMonitorClose,
    kBatteryMonitorStatusIdle,
    kBatteryMonitorStatusAnchoring,
    kBatteryMonitorStatusProbing,
    // {0}=周期序号 {1}=样本数 {2}=下次采集倒计时
    kBatteryMonitorStatusMonitoring,
    // {0}=样本数
    kBatteryMonitorStatusFinished,
    // {0}=原因
    kBatteryMonitorStatusError,
    kBatteryMonitorWarnUsbPower,
    kBatteryMonitorErrProbeTimeout,
    kBatteryMonitorErrDumpTimeout,
    kBatteryMonitorErrRestart,
    kBatteryMonitorErrDisconnected,
    kBatteryMonitorStatusWaitingReconnect,
    kBatteryMonitorErrCleared,
    kBatteryMonitorErrSaveFailed,
    kBatteryMonitorSavedTo,
    kBatteryMonitorAxisTime,
    kBatteryMonitorAxisVoltage,
    kBatteryMonitorChartTitle,
    // 供电态（USB）10min 自动关机开关（监测窗口右上角勾选框）
    kBatteryMonitorUsbAutoOff,

    // 热词预算裁剪提示（前缀 + 「保留数/总数」 + 后缀拼接）
    kHotwordTrimTitle,
    kHotwordTrimBodyPrefix,
    kHotwordTrimBodySuffix,
};

// 返回 UTF-8 本地化文本
std::string Tr(StringId id, UiLanguage language);

// 返回 UTF-16 本地化文本，适用于 Win32 宽字符 API
std::wstring TrW(StringId id, UiLanguage language);

std::string BatteryStatusText(int level_percent, bool charging, bool usb_powered, UiLanguage language);
std::wstring DeviceTitleWithBattery(const std::wstring& title,
                                    int level_percent,
                                    bool charging,
                                    bool usb_powered,
                                    UiLanguage language);

// 检查英文表和中文表是否对所有 StringId 都有非空条目
bool LocalizationTablesAreComplete();

} // namespace voicestick
